/**
 * The signature illustration: a geological cross-section from ground level
 * down to the aquifer, with a bore descending through it.
 *
 * Everything animatable is addressed by class or id so the narrative section
 * can scrub it:
 *   .geo-camera      — the group the "camera" descends through
 *   .geo-band        — the four strata fills, shallowest first
 *   .geo-edge        — the wavy boundary between bands (DrawSVG targets)
 *   .geo-texture     — specks and fracture lines, faded in per band
 *   #geo-bore        — the vertical bore line (DrawSVG target)
 *   #geo-bit         — the drill bit riding the bore
 *   #geo-glow        — the aquifer bloom
 *   .geo-tick        — depth ruler marks
 */

const EDGES = [
  "M0,86 C120,62 220,110 340,86 C460,62 520,104 600,80",
  "M0,250 C130,274 210,224 330,250 C450,276 520,230 600,256",
  "M0,486 C120,458 230,514 350,484 C470,454 530,510 600,478",
  "M0,736 C110,766 240,712 360,740 C480,768 540,714 600,744",
];

/*
 * Band colours are the `geo-band-0..3` gradients in <defs> below, generated by
 * `scripts/gen-geo.py` from its BAND_GRADS list — edit them there, not here.
 *
 * They are four distinctly different hues, not four shades of one: earth
 * brown, olive stone, slate, then water blue. Each layer has to be
 * recognisable as its own thing the moment it scrolls into frame. They are
 * also deliberately mid-tone rather than near-black — the panel sits on
 * `--ocean-deep`, and anything close to that in value just reads as the
 * section background showing through.
 */

/** Boundary lines: bright enough to read as real divisions between layers. */
const EDGE_STROKES = ["#F0D9B8", "#DCD6C0", "#9FE0F0", "#3FD0E8"];
const EDGE_OPACITY = [0.75, 0.55, 0.55, 0.65];

/** Depth ruler: 0m sits at the surface line, 120m at the deepest package. */
const TICKS = [0, 30, 60, 90, 120];
const tickY = (metres: number) => 86 + (metres / 120) * 854;

export default function GeoCrossSection({
  className = "",
  variant = "scrubbed",
}: {
  className?: string;
  /**
   * `scrubbed` — driven by SurfaceToSource. Fills its frame (`slice`, so the
   * container crops the tall viewBox) and starts with the glow and the depth
   * ruler hidden for the timeline to bring in.
   *
   * `static` — a plain illustration, as on /about. Fits the whole diagram
   * (`meet`) and paints every layer, because nothing is going to animate it.
   */
  variant?: "scrubbed" | "static";
}) {
  const isStatic = variant === "static";
  return (
    <svg
      viewBox="0 0 600 1040"
      preserveAspectRatio={
        isStatic ? "xMidYMid meet" : "xMidYMid slice"
      }
      className={className}
      role="img"
      aria-label="Cross-section of the ground from topsoil through weathered rock and fractured bedrock down to an aquifer, with a borehole descending to the water."
    >
      <defs>
        <linearGradient id="geo-sky" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#041B2D" />
          <stop offset="100%" stopColor="#0A3A5C" stopOpacity="0.45" />
        </linearGradient>
        <linearGradient id="geo-band-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#8A6440" />
          <stop offset="100%" stopColor="#63432A" />
        </linearGradient>
        <linearGradient id="geo-band-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#6E7161" />
          <stop offset="100%" stopColor="#4B4E40" />
        </linearGradient>
        <linearGradient id="geo-band-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#446780" />
          <stop offset="100%" stopColor="#2C4761" />
        </linearGradient>
        <linearGradient id="geo-band-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#14608A" />
          <stop offset="100%" stopColor="#082B41" />
        </linearGradient>
        <radialGradient id="geo-bloom" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="#3FD0E8" stopOpacity="0.95" />
          <stop offset="45%" stopColor="#3FD0E8" stopOpacity="0.28" />
          <stop offset="100%" stopColor="#3FD0E8" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="geo-bore-grad" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#E8C766" />
          <stop offset="35%" stopColor="#3FD0E8" />
          <stop offset="100%" stopColor="#3FD0E8" />
        </linearGradient>
        {/* Fractal grain, blended over the strata so the bands read as
            material rather than as flat fills. */}
        <filter id="geo-grain" x="0" y="0" width="100%" height="100%">
          <feTurbulence type="fractalNoise" baseFrequency="0.8" numOctaves="4" seed="11" stitchTiles="stitch" />
          <feColorMatrix type="saturate" values="0" />
        </filter>
      </defs>

      <g className="geo-camera">
        {/* Open air above the ground line. */}
        <rect x="0" y="0" width="600" height="130" fill="url(#geo-sky)" />

        {/* Bands, shallowest first: each fills to the bottom of the frame
            and the next paints over its lower half. A vertical gradient
            gives every layer its own light falloff. */}
        {EDGES.map((edge, index) => (
          <path
            key={`band-${index}`}
            className="geo-band"
            d={`${edge} L600,1040 L0,1040 Z`}
            fill={`url(#geo-band-${index})`}
          />
        ))}

        {/* Dark organic crust sitting on the ground line. */}
        <path
          d={EDGES[0]}
          fill="none"
          stroke="#2E2013"
          strokeOpacity="0.5"
          strokeWidth="16"
        />

        {/* Topsoil: loose grit and small stones. */}
        <g className="geo-texture" data-band="0">
          <polygon points="299.0,178.7 296.0,183.0 292.3,182.3 287.9,178.5 289.8,174.2 296.3,173.1" fill="#B08A5C" opacity="0.53" />
          <polygon points="315.5,150.9 314.4,152.6 311.8,152.3 309.5,150.8 311.6,149.0 314.4,148.7" fill="#6A4A2C" opacity="0.88" />
          <polygon points="341.8,115.8 339.1,119.2 335.2,119.2 333.6,116.1 335.8,114.2 339.1,114.6" fill="#563A22" opacity="0.82" />
          <polygon points="355.0,148.8 351.8,151.7 346.9,151.8 345.8,148.2 346.7,145.6 351.9,145.1" fill="#9C7448" opacity="0.65" />
          <polygon points="502.2,230.9 500.0,233.5 493.8,236.1 490.1,229.7 493.0,224.9 500.8,225.0" fill="#6A4A2C" opacity="0.84" />
          <polygon points="212.4,218.8 209.9,221.0 206.5,222.1 204.0,219.0 207.0,216.3 210.6,215.8" fill="#563A22" opacity="0.91" />
          <polygon points="13.1,217.3 10.1,220.2 7.4,219.7 2.6,216.9 7.1,214.7 10.0,214.4" fill="#9C7448" opacity="0.85" />
          <polygon points="253.9,226.5 252.1,230.4 247.1,230.4 244.4,226.4 247.7,222.3 252.3,223.9" fill="#9C7448" opacity="0.64" />
          <polygon points="182.1,225.6 174.7,230.6 166.7,233.5 165.1,227.3 168.2,222.1 175.7,220.8" fill="#B08A5C" opacity="0.85" />
          <polygon points="204.8,195.1 200.2,201.7 193.5,201.1 190.8,195.9 191.2,190.8 198.3,192.6" fill="#563A22" opacity="0.83" />
          <polygon points="299.7,132.8 296.5,137.1 290.1,137.2 287.0,132.6 290.0,128.9 296.3,127.1" fill="#6A4A2C" opacity="0.92" />
          <polygon points="574.9,118.1 569.9,125.2 563.0,123.7 562.5,119.0 565.0,114.3 570.6,113.8" fill="#9C7448" opacity="0.52" />
          <polygon points="571.4,109.1 567.3,112.4 561.7,115.3 557.8,108.6 562.9,104.5 566.7,104.9" fill="#563A22" opacity="0.81" />
          <polygon points="437.5,238.6 435.1,241.7 430.7,242.0 429.1,238.0 431.4,235.1 435.5,236.7" fill="#563A22" opacity="0.72" />
          <polygon points="330.2,212.6 329.8,215.3 324.2,215.4 322.5,211.6 325.5,209.6 329.2,209.1" fill="#6A4A2C" opacity="0.86" />
          <polygon points="340.5,173.2 337.2,176.3 331.9,178.9 329.6,173.9 330.9,167.4 337.3,167.2" fill="#6A4A2C" opacity="0.72" />
          <polygon points="382.3,193.9 378.6,196.1 375.7,195.6 373.7,193.3 375.7,191.1 378.1,190.2" fill="#563A22" opacity="0.74" />
          <polygon points="33.0,133.4 27.2,139.5 22.2,140.4 18.3,133.8 21.6,129.2 28.2,128.2" fill="#9C7448" opacity="0.77" />
          <polygon points="586.1,243.1 582.2,248.8 573.4,248.9 571.2,241.9 575.7,238.6 581.4,236.0" fill="#B08A5C" opacity="0.78" />
          <polygon points="79.1,116.9 76.1,123.7 69.0,123.3 63.6,116.2 67.8,110.8 77.2,109.6" fill="#B08A5C" opacity="0.81" />
          <polygon points="493.1,211.3 489.5,213.9 485.4,214.1 483.9,210.8 485.9,208.3 489.5,208.5" fill="#563A22" opacity="0.51" />
          <polygon points="46.5,146.8 44.0,148.5 41.0,148.3 40.2,146.8 40.4,144.2 43.4,144.8" fill="#563A22" opacity="0.75" />
          <polygon points="495.1,113.8 493.3,119.8 486.0,118.4 481.7,112.8 486.8,107.8 492.2,108.4" fill="#563A22" opacity="0.73" />
          <polygon points="132.8,108.7 130.8,114.3 124.9,113.9 122.4,108.9 126.0,104.5 131.0,105.7" fill="#B08A5C" opacity="0.67" />
          <polygon points="62.7,128.7 61.1,131.4 58.2,130.6 54.9,128.9 56.8,125.4 60.7,126.8" fill="#B08A5C" opacity="0.79" />
          <polygon points="137.9,124.6 134.9,127.2 129.1,128.9 126.6,124.0 129.2,120.6 136.7,120.5" fill="#6A4A2C" opacity="0.95" />
          <polygon points="258.5,173.8 254.7,176.1 250.8,177.3 249.8,173.1 251.4,170.8 256.9,169.7" fill="#563A22" opacity="0.57" />
          <polygon points="288.3,167.5 282.2,171.7 273.8,171.7 271.6,166.6 274.4,160.1 283.1,162.2" fill="#B08A5C" opacity="0.75" />
          <polygon points="218.1,189.4 215.8,190.6 214.2,191.2 212.1,188.8 213.6,187.2 216.4,187.2" fill="#B08A5C" opacity="0.75" />
          <polygon points="206.8,107.7 205.6,108.9 203.7,109.0 202.3,107.6 203.1,104.8 205.8,106.1" fill="#9C7448" opacity="0.82" />
          <polygon points="209.6,178.0 207.3,180.4 202.8,180.2 201.6,178.0 202.7,174.3 207.1,174.5" fill="#6A4A2C" opacity="0.62" />
          <polygon points="92.9,121.0 86.0,126.2 80.4,127.8 74.3,121.2 80.2,117.6 88.6,115.3" fill="#6A4A2C" opacity="0.74" />
          <polygon points="64.8,235.1 61.8,239.9 55.7,240.2 52.4,233.6 56.4,230.3 61.1,230.7" fill="#6A4A2C" opacity="0.63" />
          <polygon points="91.7,103.6 89.4,105.7 86.8,106.0 86.3,104.1 86.2,101.9 90.4,101.9" fill="#563A22" opacity="0.66" />
          <polygon points="198.3,125.4 194.9,127.5 191.1,129.5 188.4,124.3 190.8,120.8 196.1,120.0" fill="#B08A5C" opacity="0.92" />
          <polygon points="401.4,116.7 399.8,119.7 396.0,120.2 393.9,117.4 395.9,114.5 399.5,114.6" fill="#9C7448" opacity="0.88" />
        </g>

        {/* Weathered rock: rounded blocks, edges already breaking down. */}
        <g className="geo-texture" data-band="1">
          <polygon points="129.9,354.6 128.0,359.8 118.7,364.5 109.8,357.5 109.5,351.5 117.6,346.7 127.8,348.3" fill="#6E7161" opacity="0.77" />
          <polygon points="254.2,298.2 240.9,304.5 224.1,313.3 213.6,301.9 207.1,290.3 226.9,283.0 238.2,283.1" fill="#585B4C" opacity="0.47" />
          <polygon points="147.9,295.8 145.1,305.7 129.4,311.3 115.0,300.8 120.1,290.9 125.7,284.3 144.1,287.3" fill="#4E5145" opacity="0.46" />
          <polygon points="199.0,328.4 196.5,337.9 177.8,337.8 169.2,331.2 163.2,319.3 182.5,313.8 194.2,316.1" fill="#6E7161" opacity="0.76" />
          <polygon points="536.3,281.4 530.1,292.0 512.7,296.9 496.7,289.0 501.1,277.9 514.5,274.5 526.9,273.3" fill="#7C7F6C" opacity="0.60" />
          <polygon points="362.5,408.6 363.3,429.8 333.6,423.8 315.9,415.0 311.9,398.3 334.9,388.3 361.8,396.5" fill="#585B4C" opacity="0.77" />
          <polygon points="370.2,412.6 353.7,426.4 333.8,432.7 316.1,422.3 308.2,408.1 330.1,394.5 359.6,398.3" fill="#7C7F6C" opacity="0.50" />
          <polygon points="166.3,404.7 164.9,415.1 152.5,416.5 142.3,408.5 142.7,402.1 152.6,393.9 165.1,397.6" fill="#7C7F6C" opacity="0.66" />
          <polygon points="418.7,472.2 406.1,476.5 390.1,481.4 376.0,473.6 379.1,464.7 389.0,456.5 404.0,459.2" fill="#585B4C" opacity="0.78" />
          <polygon points="118.2,285.4 113.9,293.9 94.7,300.6 70.8,290.6 77.9,278.0 95.1,267.9 113.1,269.5" fill="#6E7161" opacity="0.49" />
          <polygon points="513.3,366.9 507.3,373.6 495.8,374.5 486.4,369.2 480.4,360.5 497.8,356.2 505.7,356.8" fill="#585B4C" opacity="0.46" />
          <polygon points="127.4,386.3 122.0,396.6 106.0,402.3 88.9,392.6 93.9,383.0 105.7,377.7 118.8,379.3" fill="#6E7161" opacity="0.76" />
          <polygon points="277.5,377.3 258.7,384.9 231.0,394.7 214.9,388.4 214.7,367.6 235.1,353.9 264.0,355.6" fill="#7C7F6C" opacity="0.65" />
          <polygon points="65.0,418.0 52.3,438.7 30.7,433.2 11.0,429.3 16.7,411.3 23.2,398.1 56.3,404.5" fill="#6E7161" opacity="0.68" />
          <polygon points="176.8,458.0 170.3,461.9 161.6,468.5 151.4,462.0 151.1,454.2 161.7,447.7 170.2,450.9" fill="#585B4C" opacity="0.79" />
          <polygon points="246.1,345.2 238.8,353.3 227.7,350.7 220.0,347.9 218.0,339.8 227.9,334.4 239.0,337.1" fill="#4E5145" opacity="0.50" />
          <polygon points="196.7,380.7 198.1,390.8 178.3,392.1 170.5,383.8 163.7,372.3 176.0,365.0 192.4,372.3" fill="#6E7161" opacity="0.68" />
          <polygon points="140.6,385.4 133.2,395.6 121.0,394.8 109.8,389.1 110.0,380.5 114.8,369.1 134.1,374.8" fill="#585B4C" opacity="0.56" />
          <polygon points="482.5,464.2 476.3,470.7 461.9,472.0 453.1,466.4 452.2,459.8 464.7,449.5 473.4,456.2" fill="#585B4C" opacity="0.70" />
          <polygon points="380.7,461.3 369.5,470.9 341.8,473.2 330.4,468.4 324.4,450.6 348.8,440.8 365.8,448.7" fill="#6E7161" opacity="0.65" />
          <polygon points="217.0,326.1 207.1,336.3 191.9,344.9 176.3,332.3 175.4,319.2 189.7,307.5 207.6,315.4" fill="#6E7161" opacity="0.75" />
          <polygon points="357.8,412.4 353.9,417.5 341.6,417.2 336.4,415.1 331.5,405.6 340.9,401.5 353.1,405.3" fill="#6E7161" opacity="0.45" />
        </g>

        {/* Fractured bedrock: angular shards split by the fractures that
            water actually travels along. */}
        <g className="geo-texture" data-band="2">
          <polygon points="419.9,591.0 413.3,604.9 390.9,599.2 391.5,584.6 407.8,580.0" fill="#2E4A63" opacity="0.73" />
          <polygon points="594.1,535.4 587.1,549.5 565.7,542.7 556.7,523.5 591.4,515.1" fill="#4F7690" opacity="0.63" />
          <polygon points="394.7,566.6 383.0,588.8 349.1,584.2 361.3,557.5 388.5,543.3" fill="#4F7690" opacity="0.63" />
          <polygon points="500.2,531.8 478.2,543.7 459.4,540.0 460.2,520.6 483.7,510.6" fill="#4F7690" opacity="0.72" />
          <polygon points="364.9,550.8 335.9,580.9 303.2,558.9 287.2,535.1 345.0,515.2" fill="#274056" opacity="0.58" />
          <polygon points="597.4,687.3 570.2,714.7 524.8,703.6 530.8,681.3 567.1,670.3" fill="#44677F" opacity="0.69" />
          <polygon points="349.9,651.0 325.3,674.4 294.7,667.1 293.0,634.4 322.6,641.5" fill="#2E4A63" opacity="0.72" />
          <polygon points="70.9,579.3 36.6,598.7 11.0,593.7 -2.1,563.4 37.8,557.6" fill="#4F7690" opacity="0.62" />
          <polygon points="123.9,511.9 101.0,535.6 63.4,527.9 70.6,499.8 104.2,490.1" fill="#274056" opacity="0.56" />
          <polygon points="420.1,507.8 393.0,524.6 359.1,518.1 364.8,489.5 398.3,480.2" fill="#274056" opacity="0.53" />
          <polygon points="182.3,692.9 166.7,710.1 136.1,702.8 138.2,678.6 171.2,677.4" fill="#44677F" opacity="0.81" />
          <polygon points="518.1,713.4 482.7,730.4 456.4,731.0 452.1,707.3 480.1,696.5" fill="#4F7690" opacity="0.53" />
          <polygon points="409.7,526.4 392.0,552.8 363.2,535.5 351.7,500.4 392.6,505.1" fill="#2E4A63" opacity="0.66" />
          <polygon points="125.2,516.7 87.2,555.5 46.6,543.3 47.2,506.6 85.9,497.9" fill="#4F7690" opacity="0.63" />
          <polygon points="194.4,544.6 162.9,560.4 135.8,556.4 139.0,538.6 163.0,526.4" fill="#44677F" opacity="0.78" />
          <polygon points="44.6,526.2 27.6,538.5 -11.1,533.6 -3.1,510.0 23.3,500.1" fill="#4F7690" opacity="0.63" />
          <polygon points="198.2,520.4 190.6,533.7 171.3,527.4 171.0,513.6 188.8,507.9" fill="#274056" opacity="0.58" />
          <polygon points="577.2,695.5 543.0,725.1 513.0,709.5 518.4,691.1 539.9,686.5" fill="#274056" opacity="0.56" />
          <polygon points="196.7,537.6 180.4,547.0 161.2,544.4 162.8,531.4 178.7,524.5" fill="#2E4A63" opacity="0.52" />
          <polygon points="283.2,639.0 272.5,666.3 227.1,658.2 226.5,624.7 268.9,614.8" fill="#44677F" opacity="0.54" />
          <g stroke="#A8E8F5" fill="none" strokeLinecap="round">
            <path d="M118,657 L175,625 L230,605" strokeOpacity="0.40" strokeWidth="2.1" />
            <path d="M445,725 L528,766 L601,784" strokeOpacity="0.25" strokeWidth="1.7" />
            <path d="M276,519 L315,515 L359,534" strokeOpacity="0.43" strokeWidth="1.4" />
            <path d="M363,699 L420,680 L489,683 L527,690 L578,662" strokeOpacity="0.38" strokeWidth="1.2" />
            <path d="M482,569 L538,561 L580,545 L666,540" strokeOpacity="0.25" strokeWidth="2.0" />
            <path d="M319,518 L370,552 L415,576 L478,606" strokeOpacity="0.35" strokeWidth="2.0" />
            <path d="M236,663 L322,705 L385,723 L435,742 L472,774" strokeOpacity="0.49" strokeWidth="1.2" />
            <path d="M485,584 L552,587 L588,568 L619,596 L653,639" strokeOpacity="0.36" strokeWidth="1.9" />
            <path d="M246,657 L333,632 L397,647 L471,679 L550,684" strokeOpacity="0.47" strokeWidth="1.4" />
            <path d="M336,587 L398,580 L468,548" strokeOpacity="0.36" strokeWidth="1.2" />
            <path d="M201,692 L283,682 L361,712" strokeOpacity="0.36" strokeWidth="1.5" />
            <path d="M52,531 L112,529 L189,500" strokeOpacity="0.43" strokeWidth="1.7" />
          </g>
        </g>

        {/* The aquifer: rock holding water under pressure. */}
        <g className="geo-texture" data-band="3">
          <polygon points="515.3,779.1 482.2,801.4 448.1,788.8 446.2,764.2 484.1,764.9" fill="#0B3A55" opacity="0.76" />
          <polygon points="195.8,849.3 173.4,860.9 135.9,856.7 147.1,833.8 176.4,827.8" fill="#092E45" opacity="0.55" />
          <polygon points="112.7,995.2 106.2,1018.4 57.7,1018.8 71.7,990.2 106.9,970.7" fill="#0B3A55" opacity="0.50" />
          <polygon points="600.1,1007.0 579.5,1024.5 533.7,1015.0 549.2,997.1 581.3,982.8" fill="#1A6A90" opacity="0.46" />
          <polygon points="361.7,965.5 340.8,983.2 314.5,975.7 291.6,955.5 340.1,943.5" fill="#1A6A90" opacity="0.61" />
          <polygon points="431.5,807.9 408.6,831.7 361.2,831.6 377.3,801.9 399.0,793.4" fill="#0B3A55" opacity="0.58" />
          <polygon points="452.3,837.4 427.3,852.3 384.7,860.1 403.8,828.4 435.5,809.6" fill="#1A6A90" opacity="0.53" />
          <polygon points="369.4,784.6 348.6,804.2 328.5,797.0 322.4,774.3 352.0,775.9" fill="#092E45" opacity="0.52" />
          <polygon points="435.6,910.2 400.8,938.6 353.8,930.8 363.5,902.8 393.5,894.6" fill="#092E45" opacity="0.48" />
          <polygon points="261.4,860.4 256.0,869.0 236.3,869.6 241.2,854.2 261.7,844.1" fill="#092E45" opacity="0.46" />
          <polygon points="163.4,863.1 148.1,888.7 127.4,870.1 118.7,853.8 142.5,850.6" fill="#092E45" opacity="0.77" />
          <polygon points="63.7,819.9 41.0,843.3 -4.7,840.8 9.2,807.9 46.4,802.6" fill="#1A6A90" opacity="0.63" />
          <polygon points="168.8,899.8 136.0,932.9 94.5,906.9 92.3,883.0 132.5,876.0" fill="#092E45" opacity="0.58" />
          <polygon points="386.4,1012.5 368.5,1038.9 341.1,1023.4 329.1,998.2 370.6,979.4" fill="#15597C" opacity="0.51" />
          <polygon points="412.5,851.7 395.5,863.9 363.7,862.0 371.1,837.8 392.7,837.8" fill="#1A6A90" opacity="0.46" />
          <polygon points="373.3,902.9 362.2,920.3 336.7,913.1 342.8,896.9 363.9,886.6" fill="#092E45" opacity="0.62" />
          <polygon points="580.2,796.8 564.9,814.6 517.4,818.4 501.5,777.8 566.5,771.4" fill="#0B3A55" opacity="0.58" />
          <polygon points="251.7,921.2 247.9,931.8 223.9,928.4 232.3,914.3 245.3,904.2" fill="#1A6A90" opacity="0.78" />
          <g stroke="#7FE5F5" fill="none" strokeLinecap="round">
            <path d="M0,829 C140,843 300,840 600,841" strokeOpacity="0.61" strokeWidth="2.5" />
            <path d="M0,939 C140,944 300,948 600,949" strokeOpacity="0.61" strokeWidth="2.4" />
            <path d="M0,937 C140,914 300,915 600,922" strokeOpacity="0.40" strokeWidth="2.3" />
            <path d="M0,986 C140,978 300,978 600,985" strokeOpacity="0.67" strokeWidth="2.1" />
            <circle cx="250" cy="836" r="2.7" fill="#BFF2FA" opacity="0.36" />
            <circle cx="492" cy="856" r="3.7" fill="#BFF2FA" opacity="0.42" />
            <circle cx="270" cy="842" r="2.8" fill="#BFF2FA" opacity="0.33" />
            <circle cx="380" cy="1023" r="1.9" fill="#BFF2FA" opacity="0.53" />
            <circle cx="402" cy="849" r="1.7" fill="#BFF2FA" opacity="0.49" />
            <circle cx="390" cy="885" r="1.9" fill="#BFF2FA" opacity="0.48" />
            <circle cx="122" cy="931" r="4.0" fill="#BFF2FA" opacity="0.66" />
            <circle cx="542" cy="867" r="3.8" fill="#BFF2FA" opacity="0.64" />
            <circle cx="387" cy="798" r="3.7" fill="#BFF2FA" opacity="0.34" />
            <circle cx="434" cy="850" r="2.5" fill="#BFF2FA" opacity="0.35" />
            <circle cx="547" cy="893" r="1.6" fill="#BFF2FA" opacity="0.34" />
            <circle cx="97" cy="974" r="2.5" fill="#BFF2FA" opacity="0.67" />
            <circle cx="488" cy="908" r="3.1" fill="#BFF2FA" opacity="0.63" />
            <circle cx="337" cy="967" r="3.4" fill="#BFF2FA" opacity="0.66" />
            <circle cx="493" cy="993" r="4.3" fill="#BFF2FA" opacity="0.51" />
            <circle cx="399" cy="929" r="2.1" fill="#BFF2FA" opacity="0.39" />
            <circle cx="482" cy="989" r="3.6" fill="#BFF2FA" opacity="0.59" />
            <circle cx="521" cy="962" r="2.3" fill="#BFF2FA" opacity="0.32" />
            <circle cx="338" cy="969" r="1.7" fill="#BFF2FA" opacity="0.38" />
            <circle cx="423" cy="798" r="4.2" fill="#BFF2FA" opacity="0.51" />
            <circle cx="137" cy="898" r="3.4" fill="#BFF2FA" opacity="0.25" />
            <circle cx="380" cy="955" r="1.8" fill="#BFF2FA" opacity="0.67" />
            <circle cx="462" cy="962" r="2.3" fill="#BFF2FA" opacity="0.35" />
            <circle cx="516" cy="954" r="3.3" fill="#BFF2FA" opacity="0.33" />
          </g>
        </g>

        {/* Grain across the whole profile, unifying the aggregate. */}
        <rect
          x="0"
          y="0"
          width="600"
          height="1040"
          filter="url(#geo-grain)"
          opacity="0.16"
          style={{ mixBlendMode: "overlay" }}
        />

        {/* Boundary lines between layers. */}
        {EDGES.map((edge, index) => (
          <path
            key={`edge-${index}`}
            className="geo-edge"
            d={edge}
            fill="none"
            stroke={EDGE_STROKES[index]}
            strokeOpacity={EDGE_OPACITY[index]}
            strokeWidth={index === 0 ? 2.6 : 2}
            strokeLinecap="round"
          />
        ))}

        {/* Aquifer bloom, behind the bore tip. */}
        <circle
          id="geo-glow"
          cx="300"
          cy="900"
          r="150"
          fill="url(#geo-bloom)"
          opacity={isStatic ? 1 : 0}
        />

        {/* The bore: an open shaft, its casing walls, then the bright
            progress line the timeline draws downward. */}
        <line className="geo-casing" x1="300" y1="70" x2="300" y2="900" stroke="#0A1119" strokeOpacity="0.85" strokeWidth="17" strokeLinecap="round" />
        <line className="geo-casing" x1="291" y1="86" x2="291" y2="900" stroke="#EAF6FA" strokeOpacity="0.3" strokeWidth="1.4" />
        <line className="geo-casing" x1="309" y1="86" x2="309" y2="900" stroke="#EAF6FA" strokeOpacity="0.3" strokeWidth="1.4" />
        <line id="geo-bore" x1="300" y1="56" x2="300" y2="900" stroke="url(#geo-bore-grad)" strokeWidth="3.4" strokeLinecap="round" />

        {/* Drill bit, tip pointing down, centred on y=0 so the narrative
            can simply translate it down the bore. */}
        <g id="geo-bit">
          <circle cx="300" cy="2" r="26" fill="#041B2D" fillOpacity="0.35" stroke="#E8C766" strokeOpacity="0.45" strokeWidth="1.6" />
          <path d="M300,20 C300,20 314,0 314,-9 a14,14 0 0 0 -28,0 C286,0 300,20 300,20 Z" fill="#E8C766" />
          <circle cx="300" cy="-7" r="4.5" fill="#041B2D" opacity="0.5" />
        </g>

        {/* Depth ruler. */}
        <g className="geo-ruler">
          {TICKS.map((metres) => (
            <g key={metres} className="geo-tick" opacity={isStatic ? 1 : 0}>
              <line x1="536" y1={tickY(metres)} x2="566" y2={tickY(metres)} stroke="#EAF6FA" strokeOpacity="0.45" strokeWidth="1.2" />
              <text
                x="572"
                y={tickY(metres) + 4}
                fill="#EAF6FA"
                fillOpacity="0.55"
                fontSize="15"
                fontFamily="var(--font-manrope), sans-serif"
                letterSpacing="1"
              >
                {metres}m
              </text>
            </g>
          ))}
        </g>
      </g>
    </svg>
  );
}
